repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff_check
        name: ruff check
        language: system
        entry: ruff check
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
  - repo: local
    hooks:
      - id: ruff_format
        name: ruff format
        language: system
        entry: ruff format
        types: [python]
